name: Build-SDK 24.04
on: push

jobs:
  build-linux-arm:
    name: Build SDK for Linux 24.04 arm64
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Update APT
        run:  sudo apt update
      - name: Install Host Dependencies
        run: sudo apt install cmake ninja-build gcc-14 g++-14 bison ocaml-core xz-utils pkg-config python3-pip
      - name: Install python
        run: pip3 install setuptools wheel
      - name: Install Target Dependencies
        run: | 
          sudo apt install libglm-dev libxcb-dri3-0 libxcb-present0 libpciaccess0 \
          libpng-dev libxcb-keysyms1-dev libxcb-dri3-dev libx11-dev \
          libwayland-dev libxrandr-dev libxcb-randr0-dev libxcb-ewmh-dev \
          libx11-xcb-dev liblz4-dev libzstd-dev \
          libxml2-dev wayland-protocols -y --no-install-recommends
      - name: Download SDK
        run: curl -o vulkan-sdk.tar.gz https://sdk.lunarg.com/sdk/download/latest/linux/vulkan-sdk.tar.xz
      - name: Unpack SDK
        run: tar -xJf vulkan-sdk.tar.xz
      - name: Remove x86_64
        run: | 
          cd `find . -maxdepth 1 -type d -name '1.*' -print -quit`
          rm -r x86_64
      - name: Build SDK
        run: |
          cd `find . -maxdepth 1 -type d -name '1.*' -print -quit`
          CC=/usr/bin/aarch64-linux-gnu-gcc-14 CXX=/usr/bin/aarch64-linux-gnu-g++-14 ./vulkansdk --maxjobs vulkan-loader vulkan-validationlayers vulkan-extensionlayer
      - name: Package SDK as tar.xz
        run: |
          tar -cJf vulkan-sdk-arm64.tar.xz `find . -maxdepth 1 -type d -name '1.*' -print -quit`
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vulkan-sdk-arm64
          path: vulkan-sdk-arm64.tar.xz

          
          
